### PR TITLE
Added Numbers Protocol to network

### PR DESCRIPTION
**Pull request by shc261392**
## Description

Add Numbers Protocol to network.

Numbers Mainnet is on [Chainlist.org](https://chainlist.org/chain/10507). The [SLIP-0044 update](https://github.com/satoshilabs/slips/pull/1577) is also created.

## Changes include

- [ ] Bugfix (non-breaking change that solves an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (change that is not backwards-compatible and/or changes current functionality)
- [ ] Tests
- [ ] Documentation
- [ ] Other (for changes that might not fit in any category)

### CODE REVIEW

**Comment by shc261392** [comment]
64px GIF icon:
NUM_64px

32px GIF icon:
NUM_32px

**Comment by vforgeoux-ledger** [comment]
Hello @shc261392 , can you please update your PR with [latest guidelines](https://developers.ledger.com/docs/embedded-app/eth-app-update/) ? So we can trigger the CI and see if the icons are fine. Thanks!

**Comment by shc261392** [comment]
Hi @vforgeoux-ledger , I've updated the PR with the guideline and added the icon. Thanks!

**Comment by vforgeoux-ledger** [comment]
> Hi @vforgeoux-ledger , I've updated the PR with the guideline and added the icon. Thanks!

It looks like the Stax icon doesn't pass the CI. Can you please fix it ?
Let me know if this [tool](https://github.com/LedgerHQ/embedded-application-tools) helps.

**Comment by shc261392** [comment]
@vforgeoux-ledger I've replcaed the icon with the image generated via the tool you mentioned. Could you trigger the CI again and let's see if it passes?

**Comment by vforgeoux-ledger** [comment]
> @vforgeoux-ledger I've replcaed the icon with the image generated via the tool you mentioned. Could you trigger the CI again and let's see if it passes?

✅ , remaining failing checks are on our side. Thanks @shc261392

**Comment by apaillier-ledger** [comment]
Already added in #516

**Pull request closed without merging**
