### PR TITLE
New Chain Request | Bitrock Mainnet | BROCK

### PR DESCRIPTION
**Pull request by BitrockChain**
New Chain Request for Ledger Integration
Network Name: Bitrock | BROCK
Chainlist:  https://chainlist.org/chain/7171
SLIP-0044 Merged: https://github.com/satoshilabs/slips/blob/master/slip-0044.md

### CODE REVIEW

**Comment by vforgeoux-ledger** [comment]
Hello @BitrockChain , can you please update your PR with [latest guidelines](https://developers.ledger.com/docs/embedded-app/eth-app-update/) please ?

**Comment by BitrockChain** [comment]
Hi @vforgeoux-ledger , i just add chain icon for Stax. Kindly review the changed and PR. 
Thank you.

**Comment by vforgeoux-ledger** [comment]
@BitrockChain you may want to remove .DS_Store files

**Comment by BitrockChain** [comment]
@vforgeoux-ledger .DS_Store files removed

**Comment by apaillier-ledger** [comment]
Already added in #516

**Pull request closed without merging**
