### PR TITLE
Add Celo mainnet and long-running testnets

### PR DESCRIPTION
**Pull request by kobigurk-clabs**

### CODE REVIEW

**Comment by FabriceDautriat** [comment]
@pscott @TamtamHero , many people will soon interact with the Celo blockchain through Metamask (which doesn't support the stand-alone Celo app yet). 

This PR might at least help users understand a bit better what they are doing. 

WDYT ?

**Comment by TamtamHero** [comment]
LGTM, could you please run `find . -iname '*.h' -o -iname '*.c' | xargs clang-format -i` for the linter to pass, or enable edits from maintainers on this PR so I can do it? (https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork)

**Comment by kobigurk-clabs** [comment]
DOne!

**Comment by TamtamHero** [comment]
Hem, it should be made with clang-format in version 10.0.0
Should have told you, sorry :grimacing:

**Comment by kobigurk-clabs** [comment]
Alright, seems hard to get through homebrew :) Maybe this time I'll just let you do it if that's ok!

**Comment by kobigurk-clabs** [comment]
Edits are allowed by maintainers

**Comment by pscott** [comment]
Merge into #183 :D

**Pull request closed without merging**
