### PR TITLE
add support for Theta

### PR DESCRIPTION
**Pull request by jingxu85**
Add support for Theta followed TomoChain example : https://github.com/LedgerHQ/app-ethereum/pull/58/files

### CODE REVIEW

**Comment by TamtamHero** [comment]
Hello !
Can you please sign your commits first?

**Comment by TamtamHero** [comment]
Still can't merge it, you've only signed one commit out of 2

**Comment by TamtamHero** [comment]
Also, you're missing all the icons for Theta

**Comment by jingxu85** [comment]
I can not sign all the commits in this PR. So I've created new one here : https://github.com/LedgerHQ/app-ethereum/pull/153
I'm closing this PR

**Pull request closed without merging**
