### PR TITLE
Add Core to network.c

### PR DESCRIPTION
**Pull request by denalimarsh**
Adding Core to network.c and add the stax/core logo to gylphs.

Homepage: https://coredao.org/
Documentation: https://docs.coredao.org/developer/
Chain ID: 1116
slip-0044: https://github.com/satoshilabs/slips/pull/1629/files

### CODE REVIEW

**Comment by vforgeoux-ledger** [comment]
Hello @denalimarsh , looks like the Stax icon doesn't pass the CI. Can you please fix it ? 
Here is the [template](https://developers.ledger.com/docs/embedded-app/icons/#stax-template), this [tool](https://github.com/LedgerHQ/embedded-application-tools) may help as well.

**Comment by denalimarsh** [comment]
@vforgeoux-ledger generated a new Stax icon using the tool and updated the PR. Could you rerun the CI? Thanks!

**Comment by vforgeoux-ledger** [comment]
> @vforgeoux-ledger generated a new Stax icon using the tool and updated the PR. Could you rerun the CI? Thanks!

✅ , remaining failing checks are on our side. Thanks @denalimarsh

**Comment by apaillier-ledger** [comment]
Already added in #516

**Pull request closed without merging**
