### PR TITLE
Add Electroneum Mainnet/Testnet to supported networks

### PR DESCRIPTION
**Pull request by andrepatta**
## Description

Add Electroneum Mainnet/Testnet to supported networks in Ethereum Ledger App.
## Changes include

- [ ] Bugfix (non-breaking change that solves an issue)
- [X] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (change that is not backwards-compatible and/or changes current functionality)
- [ ] Tests
- [ ] Documentation
- [ ] Other (for changes that might not fit in any category)

## Additional comments

Resources:
- Website: https://electroneum.com/
- Twitter: https://twitter.com/electroneum
- Block Explorer: https://blockexplorer.electroneum.com/
- Project Documentation: https://developer.electroneum.com/
- ChainList.org: https://chainlist.org/?search=ETN&testnets=true
- Slip-0044: https://github.com/satoshilabs/slips/blob/master/slip-0044.md (**Coin type:** 415; **Path component:** 0x8000019f; **Symbol:** ETN; **Coin:** Electroneum;

### CODE REVIEW

**Comment by vforgeoux-ledger** [comment]
Hey @andrepatta , it looks like your icon doesn't respect the guidelines (background should be white)

**Comment by andrepatta** [comment]
Hi @vforgeoux-ledger thanks for letting me know. Is it okay if I submit the correct icon on Monday?

**Comment by vforgeoux-ledger** [comment]
Yes @andrepatta , we want to merge networks PR today 🙏

**Comment by andrepatta** [comment]
Should be done @vforgeoux-ledger

**Comment by vforgeoux-ledger** [comment]
Included in https://github.com/LedgerHQ/app-ethereum/pull/598

**Pull request closed without merging**
