### PR TITLE
feat: add bob

### PR DESCRIPTION
**Pull request by gregdhill**
## Description

Added BOB mainnet chain id, see [Chainlist](https://chainlist.org/?search=bob).

## Changes include

- [ ] Bugfix (non-breaking change that solves an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (change that is not backwards-compatible and/or changes current functionality)
- [ ] Tests
- [ ] Documentation
- [ ] Other (for changes that might not fit in any category)

### CODE REVIEW

**Comment by vforgeoux-ledger** [comment]
Hey @gregdhill , thanks for your PR ! It seems that we are missing your 64px icon in the glyphs folder though. You should find more informations [here](https://developers.ledger.com/docs/device-app/develop/code/clone#2-add-an-icon-for-ledger-stax) on how to craft one.

Note : The naming format for the glyphs icon will soon be updated on the developer portal, but it should now be `chain_yourchainid_64px.gif`

**Comment by vforgeoux-ledger** [comment]
Hi @gregdhill , we want to merge the new networks PR today, so can you please have a look ?

**Comment by gregdhill** [comment]
@vforgeoux-ledger added the glyph icon now using the new format. Let me know if that will suffice.

**Comment by vforgeoux-ledger** [comment]
It doesn't respect exactly the guidelines. I've crafted this one for you : 
chain_60808_64px
Does it suit you ?

**Comment by gregdhill** [comment]
@vforgeoux-ledger assuming the logo should be square? I don't think that is mentioned explicitly in the guidelines. Uploaded a new version now, please check

**Comment by vforgeoux-ledger** [comment]
I did the [commit](https://github.com/LedgerHQ/app-ethereum/pull/598/commits/b3d679ff2ba6adfca26752ac30e6d2be16a3d748) with one I crafted. Let me know if you really want the full black to replace it @gregdhill

**Comment by gregdhill** [comment]
Ah no should be all black @vforgeoux-ledger but can you let us know what guideline we are still missing?

**Comment by vforgeoux-ledger** [comment]
I just pushed on my branch the new one you sent. Your change respects the guidelines now (apart from the file naming)

**Comment by vforgeoux-ledger** [comment]
Included in https://github.com/LedgerHQ/app-ethereum/pull/598

**Pull request closed without merging**
