### PR TITLE
Add and update PulseChain Networks

### PR DESCRIPTION
**Pull request by bretep**
## Description

Please provide a detailed description of what was done in this PR.
(And mentioned if linked to an issue [docs](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue))

## Changes include

- [ ] Bugfix (non-breaking change that solves an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (change that is not backwards-compatible and/or changes current functionality)
- [ ] Tests
- [ ] Documentation
- [ ] Other (for changes that might not fit in any category)

## Additional comments

Support for PulseChain was missed during updates earlier this year. I've added it back following the new patterns.

Ledger Live integration: https://github.com/LedgerHQ/ledger-live/pull/7607

### CODE REVIEW

**Comment by apaillier-ledger** [comment]
Hello @bretep, thank you for this PR.

We now don't allow clone applications (with separate .mk files) that only use Ethereum's derivation path, since they will work just fine directly with the Ethereum app directly.

If you could update your PR by :
* removing the two .mk files you added
* removing the .gif files you added in icons/
* since the glyphs for the mainnet and testnet are the same, to save space in both the repository and the app itself, create a symbolic link instead so that `chain_943_64px.gif` points to `chain_369_64px.gif`

Thank you! :pray:

**Comment by bretep** [comment]
@apaillier-ledger, Thank you for that excellent review and feedback.

I've done the following:

- Removed the two `.mk` files
- Removed the `.gif` icons located in `./icons`
- Symlinked the chain's `.gif` in `./glyphs` to save space
- Amended the previous commit to keep this a single commit
- Force pushed

Please let me know if I need to fix anything else. I appreciate your help.

**Comment by bretep** [comment]
@apaillier-ledger I guess the only concern I have is `DEFINES += HAVE_ETH2`. Because PulseChain has a beacon chain and uses the same BLS curve as Ethereum, will validators still be able to use the Ethereum App to make validator addresses?

Most other Ethereum chains do not have a beacon chain; they use ETH1. 

Reference:
https://beacon.pulsechain.com
https://launchpad.pulsechain.com

**Comment by apaillier-ledger** [comment]
@bretep, it should behave with the Ethereum app the same way as it would have with the separate clone app.
Let us know if you have issues between your beacon chain and the Ethereum app, since the ETH2 support was initially developped for the mainnet one.

**Review by apaillier-ledger — APPROVED** [review]

**Pull request merged**
