### PR TITLE
Add KCC Chain with ChainID = 321 as ETH clones

### PR DESCRIPTION
**Pull request by lingyun92**
## Description

Addition of KCC(KUCOIN Chain) network as ETH clones.

- Homepage:  [https://kcc.io](https://kcc.io)
- Doc: [https://docs.kcc.io](https://docs.kcc.io)
- ChainID: 321
- Chainlist: [https://chainlist.org/chain/321](https://chainlist.org/chain/321)

## Changes include

- KCC

### CODE REVIEW

**Comment by apaillier-ledger** [comment]
Hello, thank you for the PR.
With the merge of #372, your changes have a very small conflict with develop, please rebase/merge to fix it. :+1:

**Comment by lingyun92** [comment]
> 

Conflict fixed, Thanks.

**Comment by apaillier-ledger** [comment]
Much better, but last request can you make it last in the list (after the 3 Scroll), to keep the historical order. Once done I'll go ahead and merge it. Thanks. :+1:

**Comment by lingyun92** [comment]
> Much better, but last request can you make it last in the list (after the 3 Scroll), to keep the historical order intact. Once done I'll go ahead and merge it. Thanks. 👍

Sorry for the order, changed it.

**Review by apaillier-ledger — APPROVED** [review]

**Pull request merged**
