### PR TITLE
Add zkSync to networks.c

### PR DESCRIPTION
**Pull request by ischasny**
## Description

Add `zkSync Mainnet` and `zkSync Sepolia` to `networks.c`

## Changes include

- [ ] Bugfix (non-breaking change that solves an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (change that is not backwards-compatible and/or changes current functionality)
- [ ] Tests
- [ ] Documentation
- [ X ] Other (for changes that might not fit in any category)

### CODE REVIEW

**Review by shahar4 — APPROVED** [review]

**Comment by vforgeoux-ledger** [comment]
Hey @ischasny ,
Can you please update your PR to follow the [guidelines](https://developers.ledger.com/docs/device-app/develop/code/clone#a---using-the-4460-path) ?
(64px icon only is required, and should be renamed)

**Comment by ischasny** [comment]
> Hey @ischasny , Can you please update your PR to follow the [guidelines](https://developers.ledger.com/docs/device-app/develop/code/clone#a---using-the-4460-path) ? (64px icon only is required)

@vforgeoux-ledger - done

**Comment by vforgeoux-ledger** [comment]
@ischasny shouldn't we name the network **zkSync** instead of **ZKsync** ?

**Comment by ischasny** [comment]
> @ischasny shouldn't we name the network **zkSync** instead of **ZKsync** ?

@vforgeoux-ledger  This is the official branding as of the last week.

**Comment by vforgeoux-ledger** [comment]
@ischasny Please check the CI error, your icon doesn't respect the guidelines as it doesn't have a white background

**Comment by ischasny** [comment]
> @ischasny Please check the CI error, your icon doesn't respect the guidelines as it doesn't have a white background

Thank  you for pointing this out - fixed.

**Comment by vforgeoux-ledger** [comment]
Included in https://github.com/LedgerHQ/app-ethereum/pull/598

**Pull request closed without merging**
